version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.12

    steps:
      - checkout

      # Project Environment Setup
      - run: chmod +x project_setup.sh
      - run:
          name: Setting Up Project Environment
          command: ./project_setup.sh

      # Run Gradle Build
      - run: chmod +x gradlew
      - run:
          name: Android Gradle Build
          command: ./gradlew clean assemble bundle --stacktrace

      # Store Build Files
      - store_artifacts:
          path: app/build/outputs/apk
      - store_artifacts:
          path: app/build/outputs/bundle









